# TradingBotR1000 reliability policy.
# Never restart daemons automatically after package upgrades.
# Planned weekend maintenance may explicitly override with NEEDRESTART_MODE=a.
$nrconf{restart} = 'l';
